/*
 * (c) Copyright 2005-2015 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-selenium-primefaces:src/test/java/selenium/pages/entity/EditPage.e.vm.java
 */
package com.h2.demo.web.selenium.page.legacy;

import com.h2.demo.web.selenium.support.Page;
import com.h2.demo.web.selenium.support.elements.CustomWebElement;
import com.h2.demo.web.selenium.support.elements.EditAction;
import com.h2.demo.web.selenium.support.elements.EntityAction;
import com.h2.demo.web.selenium.support.elements.IntegerInput;
import com.h2.demo.web.selenium.support.elements.Messages;
import com.h2.demo.web.selenium.support.elements.StringInput;

@Page
public class LegacyEdit {
    public EditAction action;
    public Messages messages;
    public EntityAction entity;
    public LegacyEditForm form;
    public LegacyEditTabs tabs;

    public static class LegacyEditForm extends CustomWebElement {
        public StringInput name = new StringInput("form:name");
        public StringInput code = new StringInput("form:code");
        public IntegerInput dept = new IntegerInput("form:dept");
        public StringInput extraInfo = new StringInput("form:extraInfo");
    };

    public static class LegacyEditTabs extends CustomWebElement {
    };
}