/*
 * (c) Copyright 2005-2015 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/main/java/printer/Printer.e.vm.java
 */
package com.h2.demo.printer;

import java.util.Locale;

import javax.inject.Named;
import javax.inject.Singleton;

import com.h2.demo.domain.Book;
import com.h2.demo.domain.Book_;
import com.h2.demo.printer.support.GenericPrinter;

/**
 * {@link GenericPrinter} for {@link Book} 
 *
 * @see GenericPrinter
 * @see TypeAwarePrinter
 */
@Named
@Singleton
public class BookPrinter extends GenericPrinter<Book> {
    public BookPrinter() {
        super(Book.class, Book_.title);
    }

    @Override
    public String print(Book book, Locale locale) {
        if (book == null) {
            return "";
        }
        StringBuilder ret = new StringBuilder();
        appendIfNotEmpty(ret, book.getTitle());
        return ret.toString();
    }
}