/*
 * (c) Copyright 2005-2015 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-jsf2-spring-conversation:src/main/java/domain/GraphLoader.e.vm.java
 */
package com.h2.demo.web.domain;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import com.h2.demo.domain.Account;
import com.h2.demo.repository.AccountRepository;
import com.h2.demo.repository.support.EntityGraphLoader;

/**
 * Preloads the {@link Account} associations required by the view layer.
 * 
 * Do not use other GraphLoaders in this GraphLoader. 
 */
@Named
@Singleton
public class AccountGraphLoader extends EntityGraphLoader<Account, String> {
    // required by cglib to create a proxy around the object as we are using the @Transactional annotation
    protected AccountGraphLoader() {
        super();
    }

    @Inject
    public AccountGraphLoader(AccountRepository accountRepository) {
        super(accountRepository);
    }

    @Override
    public void loadGraph(Account account) {
        loadSingular(account.getAddress());
        loadCollection(account.getRoles());
    }
}