/*
 * (c) Copyright 2005-2015 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-jsf2-spring-conversation:src/main/java/domain/Controller.e.vm.java
 */
package com.h2.demo.web.domain;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import com.h2.demo.domain.Legacy;
import com.h2.demo.domain.LegacyPk;
import com.h2.demo.printer.LegacyPrinter;
import com.h2.demo.repository.LegacyRepository;
import com.h2.demo.web.domain.support.GenericController;
import com.h2.demo.web.permission.LegacyPermission;

/**
 * Stateless controller for {@link Legacy} conversation start.
 */
@Named
@Singleton
public class LegacyController extends GenericController<Legacy, LegacyPk> {
    public static final String LEGACY_EDIT_URI = "/domain/legacyEdit.faces";
    public static final String LEGACY_SELECT_URI = "/domain/legacySelect.faces";

    @Inject
    public LegacyController(LegacyRepository legacyRepository, LegacyPermission legacyPermission, LegacyPrinter legacyPrinter) {
        super(legacyRepository, legacyPermission, legacyPrinter, LEGACY_SELECT_URI, LEGACY_EDIT_URI);
    }
}