/*
 * (c) Copyright 2005-2015 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-jsf2-spring-conversation:src/main/java/domain/EditForm.e.vm.java
 */
package com.h2.demo.web.domain;

import javax.inject.Inject;
import javax.inject.Named;

import com.h2.demo.domain.Legacy;
import com.h2.demo.domain.LegacyPk;
import com.h2.demo.repository.LegacyRepository;
import com.h2.demo.web.domain.support.GenericEditForm;
import com.h2.demo.web.faces.ConversationContextScoped;

/**
 * View Helper/Controller to edit {@link Legacy}.
 */
@Named
@ConversationContextScoped
public class LegacyEditForm extends GenericEditForm<Legacy, LegacyPk> {
    @Inject
    protected LegacyController legacyController;

    @Inject
    public LegacyEditForm(LegacyRepository legacyRepository) {
        super(legacyRepository);
    }

    /**
     * The entity to edit/view.
     */
    public Legacy getLegacy() {
        return getEntity();
    }

    public String print() {
        return legacyController.print(getLegacy());
    }
}
