/*
 * (c) Copyright 2005-2015 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-jsf2-spring-conversation:src/main/java/domain/EditForm.e.vm.java
 */
package com.h2.demo.web.domain;

import java.math.BigDecimal;

import javax.inject.Inject;
import javax.inject.Named;

import com.h2.demo.domain.MoreTypesDemo;
import com.h2.demo.repository.MoreTypesDemoRepository;
import com.h2.demo.web.domain.support.GenericEditForm;
import com.h2.demo.web.faces.ConversationContextScoped;

/**
 * View Helper/Controller to edit {@link MoreTypesDemo}.
 */
@Named
@ConversationContextScoped
public class MoreTypesDemoEditForm extends GenericEditForm<MoreTypesDemo, BigDecimal> {
    @Inject
    protected MoreTypesDemoController moreTypesDemoController;

    @Inject
    public MoreTypesDemoEditForm(MoreTypesDemoRepository moreTypesDemoRepository) {
        super(moreTypesDemoRepository);
    }

    /**
     * The entity to edit/view.
     */
    public MoreTypesDemo getMoreTypesDemo() {
        return getEntity();
    }

    public String print() {
        return moreTypesDemoController.print(getMoreTypesDemo());
    }
}
