/*
 * (c) Copyright 2005-2015 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-jsf2-spring-conversation:src/main/java/domain/ExcelExporter.e.vm.java
 */
package com.h2.demo.web.domain;

import javax.inject.Inject;
import javax.inject.Named;

import com.h2.demo.domain.SavedSearch;
import com.h2.demo.web.domain.support.GenericExcelExporter;
import com.h2.demo.web.faces.ConversationContextScoped;

/**
 * Exports to excel document {@link SavedSearch} search criteria and result. 
 */
@Named
@ConversationContextScoped
public class SavedSearchExcelExporter extends GenericExcelExporter<SavedSearch> {
    @Inject
    protected SavedSearchSearchForm sf;

    public SavedSearchExcelExporter() {
        super("savedSearch_name", "savedSearch_formClassname");
    }

    @Override
    protected void fillResultItem(int row, SavedSearch item) {
        int col = 0;
        setValue(row, col++, item.getName());
        setValue(row, col++, item.getFormClassname());
    }

    @Override
    public void fillSearchCriteria(int row) {
        useCriteriaSheet();

        setSelector(row++, 0, "savedSearch_name", sf.getNameSelector());
        setSelector(row++, 0, "savedSearch_formClassname", sf.getFormClassnameSelector());
        setSelectedEntities(row++, 0, "savedSearch_account", sf.getAccountSelector().getSelected());
    }
}