/*
 * (c) Copyright 2005-2015 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-jsf2-spring-conversation:src/main/java/domain/EditForm.e.vm.java
 */
package com.h2.demo.web.domain;

import javax.annotation.PostConstruct;
import javax.inject.Inject;
import javax.inject.Named;

import com.h2.demo.domain.Account;
import com.h2.demo.domain.SavedSearch;
import com.h2.demo.domain.SavedSearch_;
import com.h2.demo.repository.SavedSearchRepository;
import com.h2.demo.web.domain.support.GenericEditForm;
import com.h2.demo.web.domain.support.GenericToOneAssociation;
import com.h2.demo.web.faces.ConversationContextScoped;

/**
 * View Helper/Controller to edit {@link SavedSearch}.
 */
@Named
@ConversationContextScoped
public class SavedSearchEditForm extends GenericEditForm<SavedSearch, Integer> {
    @Inject
    protected SavedSearchController savedSearchController;
    @Inject
    protected AccountController accountController;
    protected GenericToOneAssociation<Account, String> account;

    @Inject
    public SavedSearchEditForm(SavedSearchRepository savedSearchRepository, SavedSearchGraphLoader savedSearchGraphLoader) {
        super(savedSearchRepository, savedSearchGraphLoader);
    }

    /**
     * The entity to edit/view.
     */
    public SavedSearch getSavedSearch() {
        return getEntity();
    }

    public String print() {
        return savedSearchController.print(getSavedSearch());
    }

    @PostConstruct
    void setupAccountActions() {
        account = new GenericToOneAssociation<Account, String>(accountController, SavedSearch_.account) {
            @Override
            protected Account get() {
                return getSavedSearch().getAccount();
            }

            @Override
            protected void set(Account account) {
                getSavedSearch().setAccount(account);
            }
        };
    }

    public GenericToOneAssociation<Account, String> getAccount() {
        return account;
    }
}
